# Generated by Django 2.1.7 on 2019-04-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_remove_task_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_dec',
            new_name='task_desc',
        ),
    ]
