# Generated by Django 2.1.7 on 2019-04-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(max_length=7)),
                ('student_name', models.CharField(max_length=20)),
                ('marks', models.IntegerField(max_length=4)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
