# Generated by Django 2.1.7 on 2019-04-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='empid',
            new_name='st_id',
        ),
    ]
